// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1r7WdaEcN5ci_NC5DSpVZ7jT9-EAgs5U',
    appId: '1:467686823029:web:63f010b88ef99e46d1543c',
    messagingSenderId: '467686823029',
    projectId: 'lab-030-31bd7',
    authDomain: 'lab-030-31bd7.firebaseapp.com',
    storageBucket: 'lab-030-31bd7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW7X1exevxT8LGgSpZ_V-Klv3FAPbmTPQ',
    appId: '1:467686823029:android:7f35c1fe6dbccc3ed1543c',
    messagingSenderId: '467686823029',
    projectId: 'lab-030-31bd7',
    storageBucket: 'lab-030-31bd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAR9L2VPhFY0StSRFFAol7vqWDgfDOow',
    appId: '1:467686823029:ios:c149776af91cf3ddd1543c',
    messagingSenderId: '467686823029',
    projectId: 'lab-030-31bd7',
    storageBucket: 'lab-030-31bd7.firebasestorage.app',
    iosClientId: '467686823029-e773b8oala7h4ph09ol8i1jvv7itl6ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8030',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABAR9L2VPhFY0StSRFFAol7vqWDgfDOow',
    appId: '1:467686823029:ios:c149776af91cf3ddd1543c',
    messagingSenderId: '467686823029',
    projectId: 'lab-030-31bd7',
    storageBucket: 'lab-030-31bd7.firebasestorage.app',
    iosClientId: '467686823029-e773b8oala7h4ph09ol8i1jvv7itl6ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8030',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1r7WdaEcN5ci_NC5DSpVZ7jT9-EAgs5U',
    appId: '1:467686823029:web:a35937cc4490bb06d1543c',
    messagingSenderId: '467686823029',
    projectId: 'lab-030-31bd7',
    authDomain: 'lab-030-31bd7.firebaseapp.com',
    storageBucket: 'lab-030-31bd7.firebasestorage.app',
  );
}
